// @ts-check

/**
 * Creating a sidebar enables you to:
 * - create an ordered group of docs
 * - render a sidebar for each doc of that group
 * - provide next/previous navigation
 *
 * The sidebars can be generated from the filesystem, or explicitly defined here.
 *
 * @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // Sidebar for your AI Robotics Book
  tutorialSidebar: [
    'intro', // Root document that serves as /docs/intro
    {
      type: 'category',
      label: 'Module 1: Introduction to Physical AI',
      items: [
        { type: 'autogenerated', dirName: 'Module 1 - introduction-to-physical-ai' },
      ],
    },
    {
      type: 'category',
      label: 'Module 2: Robotic Nervous System',
      items: [
        { type: 'autogenerated', dirName: 'Module 2 - Robotic-Nervous-System' },
      ],
    },
    {
      type: 'category',
      label: 'Module 3: Digital Twin',
      items: [
        { type: 'autogenerated', dirName: 'Module 3 -Digital Twin' },
      ],
    },
    {
      type: 'category',
      label: 'Module 4: The AI-Robot Brain (NVIDIA Isaac)',
      items: [
        { type: 'autogenerated', dirName: 'Module_4_-_The_AI_Robot_Brain_NVIDIA_Isaac' },
      ],
    },
  ],
};

export default sidebars;
